# Generated by Django 6.0.3 on 2026-03-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('agricultural_sector', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('credit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='credits.creditplan')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.producerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producer', 'credit_plan'), name='unique_application_per_producer_per_plan')],
            },
        ),
    ]
