# Generated by Django 6.0.3 on 2026-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revision'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
