# Generated by Django 6.0.3 on 2026-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_companyprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='descripcion',
            field=models.TextField(blank=True, help_text="Breve reseña 'Sobre nosotros'", null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='direccion_fiscal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal completo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telefono_corporativo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tiempo_respuesta',
            field=models.CharField(blank=True, help_text='Ej: 5 días hábiles', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('BANCO', 'Banco'), ('FONDO_PRIVADO', 'Fondo Privado'), ('COOPERATIVA', 'Cooperativa'), ('INVERSIONISTA', 'Inversionista')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='cedula_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='inventario_maquinaria',
            field=models.TextField(blank=True, help_text='Descripción de tractores, equipos, etc.', null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='rubro_principal',
            field=models.CharField(blank=True, help_text='Ej: Maíz, Ganado, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='superficie_cultivada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hectáreas activas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='superficie_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hectáreas totales', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='tenencia_tierra',
            field=models.CharField(blank=True, choices=[('PROPIEDAD', 'Propiedad'), ('ARRENDADO', 'Arrendado'), ('ADJUDICACION', 'Adjudicación')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='vialidad',
            field=models.CharField(blank=True, choices=[('OPTIMA', 'Óptima'), ('REGULAR', 'Regular'), ('DIFICIL', 'Difícil')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='farm_name',
            field=models.CharField(max_length=150, verbose_name='Nombre Fundo / Farm Name'),
        ),
    ]
