# Generated by Django 6.0.3 on 2026-04-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyprofile_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='telefono_corporativo',
            new_name='corporate_phone',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='direccion_fiscal',
            new_name='fiscal_address',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='sitio_web',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='producerprofile',
            old_name='cedula_identidad',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='producerprofile',
            old_name='telefono',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='tiempo_respuesta',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='tipo_empresa',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='inventario_maquinaria',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='rubro_principal',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='superficie_cultivada',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='superficie_total',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='tenencia_tierra',
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='vialidad',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank'), ('PRIVATE_FUND', 'Private Fund'), ('COOPERATIVE', 'Cooperative'), ('INVESTOR', 'Investor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, help_text="Brief 'About us' review", null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Full legal name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='response_time',
            field=models.CharField(blank=True, help_text='Ex: 5 business days', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='cultivated_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Active hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='land_tenure',
            field=models.CharField(blank=True, choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('AWARDED', 'Awarded')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='machinery_inventory',
            field=models.TextField(blank=True, help_text='Description of tractors, equipment, etc.', null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='main_activity',
            field=models.CharField(blank=True, help_text='Ex: Corn, Cattle, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='road_condition',
            field=models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('REGULAR', 'Regular'), ('DIFFICULT', 'Difficult')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hectares', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='farm_name',
            field=models.CharField(max_length=150, verbose_name='Farm Name'),
        ),
    ]
